name: oc-review-mock-dev

services:
  app:
    build:
      context: "docker/app/"
    ports:
      - "${WEB_PORT_DEV:-8100}:80"
      - "${HTTPS_PORT_DEV:-8543}:443"
    working_dir: /var/www/html
    user: "1000:1000"
    volumes:
      - "./:/var/www/html"
      - "./docker/app/apache2/apache2.conf:/etc/apache2/apache2.conf"
      - "./docker/app/apache2/sites-available/000-default-mock.conf:/etc/apache2/sites-available/000-default.conf"
      - "./docker/app/apache2/sites-available/000-default-mock.conf:/etc/apache2/sites-enabled/000-default.conf"
      - "./docker/app/apache2/sites-available/000-default-ssl-mock.conf:/etc/apache2/sites-available/000-default-ssl.conf"
      - "./docker/app/apache2/sites-available/000-default-ssl-mock.conf:/etc/apache2/sites-enabled/000-default-ssl.conf"
      - "./docker/app/ssl-new/ocgraph.test+4.pem:/etc/ssl/certs/ocgraph.test+4.pem"
      - "./docker/app/ssl-new/ocgraph.test+4-key.pem:/etc/ssl/certs/ocgraph.test+4-key.pem"
      - "./docker/mysql/server.cnf:/etc/mysql/mariadb.conf.d/server.cnf"
    depends_on:
      - mysql
      - line-mock-api
    extra_hosts:
      - "openchat.line.me:172.30.0.10"
      - "line.me:172.30.0.10"
      - "obs.line-scdn.net:172.30.0.10"
    networks:
      dev-network:
        ipv4_address: 172.30.0.2
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2

  mysql:
    build:
      context: "docker/mysql/"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test_db_name
      - MYSQL_HOST=mysql
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_pass
      - MYSQL_ROOT_PASSWORD=test_root_pass
      - TZ=Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
      - "./docker/mysql/server.cnf:/etc/mysql/mariadb.conf.d/server.cnf"
    ports:
      - "${MYSQL_PORT_DEV:-3308}:3306"
    networks:
      dev-network:
        ipv4_address: 172.30.0.3

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "${PHP_MY_ADMIN_PORT_DEV:-8180}:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=test_root_pass
    depends_on:
      - mysql
    networks:
      dev-network:
        ipv4_address: 172.30.0.4

  # LINE公式サイトエミュレーションサーバー
  line-mock-api:
    build:
      context: "docker/line-mock-api/"
    ports:
      - "${LINE_MOCK_PORT_DEV:-9000}:80"
    volumes:
      - "./docker/line-mock-api:/app"
      - "./storage:/var/www/html/storage"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
    networks:
      dev-network:
        ipv4_address: 172.30.0.10

networks:
  dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  mysql_data:
  storage:
